language: node_js
node_js: stable
install:
- npm install
addons:
- ssh_known_hosts: 207.148.97.207
before_install:
- openssl aes-256-cbc -K $encrypted_f10c947dd520_key -iv $encrypted_f10c947dd520_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- npm install -g hexo
- npm install -g hexo-cli
script:
- hexo clean
- hexo generate
- export HEXO_ALGOLIA_INDEXING_KEY=57804367b189015886ebad2958f5aa33
- hexo algolia
- hexo deploy
after_script:
- cd ./public
- git init
- git config user.name "LaoHu47"
- git config user.email "962271461@qq.com"
- git add .
- git commit -m "Update docs"
- git push -f -q "https://${GH_TOKEN}@${GH_REF}" master:gh-pages
branches:
  only:
  - master
env:
  global:
  - GH_REF: github.com/LaoHu97/LaoHu97.github.io
