language: ''
install:
- npm install
before_install:
- npm install -g hexo
- npm install -g hexo-cli
script:
- hexo clean
- hexo generate
- export HEXO_ALGOLIA_INDEXING_KEY=57804367b189015886ebad2958f5aa33
- hexo algolia
- ssh -o "StrictHostKeyChecking no" root@207.148.97.207
- hexo deploy
after_script:
- cd ./public
- git init
- git config user.name "LaoHu47"
- git config user.email "962271461@qq.com"
- git add .
- git commit -m "Update docs"
- git push -f -q "https://${GH_TOKEN}@${GH_REF}" master:gh-pages
branches:
  only:
  - master
env:
  global:
  - GH_REF: github.com/LaoHu97/LaoHu97.github.io
