language: node_js
node_js: stable
install:
- npm install
addons:
- ssh_known_hosts: 207.148.97.207
before_install:
- openssl aes-256-cbc -K $encrypted_2f78f1094c6c_key -iv $encrypted_2f78f1094c6c_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- echo -e "Host 207.148.97.207\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- npm install -g hexo
- npm install -g hexo-cli
- curl -O -L http://downloads.sourceforge.net/project/sshpass/sshpass/1.05/sshpass-1.05.tar.gz
  && tar xvzf sshpass-1.05.tar.gz && cd sshpass-1.05 && ./configure && make && sudo
  make install
script:
- hexo clean
- hexo generate
- export HEXO_ALGOLIA_INDEXING_KEY=57804367b189015886ebad2958f5aa33
- hexo algolia
- sshpass -p 'Tx.9g@8syHxb*rAj' hexo deploy
after_script:
- cd ./public
- git init
- git config user.name "LaoHu47"
- git config user.email "962271461@qq.com"
- git add .
- git commit -m "Update docs"
- git push -f -q "https://${GH_TOKEN}@${GH_REF}" master:gh-pages
branches:
  only:
  - master
env:
  global:
  - GH_REF: github.com/LaoHu97/LaoHu97.github.io
