language: ''
install:
- npm install
before_install:
# - openssl aes-256-cbc -K $encrypted_f10c947dd520_key -iv $encrypted_f10c947dd520_iv
#   -in id_rsa.enc -out ~/.ssh/id_rsa -d
# - chmod 600 ~/.ssh/id_rsa
# - echo -e "Host 45.77.47.155\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- npm install -g hexo
- npm install -g hexo-cli
script:
- hexo clean
- hexo generate
after_script:
# - rsync -rv --delete -e 'ssh -o stricthostkeychecking=no -p 22' public/ root@45.77.47.155:/www/wwwroot/lao47
- cd ./public
- git init
- git config user.name "LaoHu47"
- git config user.email "962271461@qq.com"
- git add .
- git commit -m "Update docs"
- git push -f -q "https://${GH_TOKEN}@${GH_REF}" master:gh-pages
branches:
  only:
  - master
env:
  global:
  - GH_REF: github.com/LaoHu97/LaoHu97.github.io
